# Generated by Django 3.2.5 on 2021-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['-published_datetime'], name='video_app_f_publish_2712f9_idx'),
        ),
    ]
