# Generated by Django 3.2.5 on 2021-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20210725_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vide',
            new_name='Video',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='video_app_v_publish_cdd773_idx',
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-published_datetime'], name='video_app_v_publish_262147_idx'),
        ),
    ]
